<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200511230133 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE address CHANGE city_id city_id INT UNSIGNED DEFAULT NULL, CHANGE country_id country_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE line2 line2 VARCHAR(150) DEFAULT NULL, CHANGE zip_code zip_code VARCHAR(10) DEFAULT NULL, CHANGE longitude longitude DOUBLE PRECISION DEFAULT NULL, CHANGE latitude latitude DOUBLE PRECISION DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE city CHANGE country_id country_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE command CHANGE user_id user_id INT UNSIGNED DEFAULT NULL, CHANGE shipping_id shipping_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE status_id status_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE billing_address_id billing_address_id INT UNSIGNED DEFAULT NULL, CHANGE shipping_address_id shipping_address_id INT UNSIGNED DEFAULT NULL, CHANGE session_id session_id VARCHAR(50) DEFAULT NULL, CHANGE reference reference VARCHAR(50) DEFAULT NULL, CHANGE sub_total_vat_exc sub_total_vat_exc DOUBLE PRECISION DEFAULT NULL, CHANGE sub_total_vat_inc sub_total_vat_inc DOUBLE PRECISION DEFAULT NULL, CHANGE total_vat total_vat DOUBLE PRECISION DEFAULT NULL, CHANGE reduction_label reduction_label VARCHAR(255) DEFAULT NULL, CHANGE reduction reduction DOUBLE PRECISION DEFAULT NULL, CHANGE shipping_label shipping_label VARCHAR(255) DEFAULT NULL, CHANGE shipping_value shipping_value DOUBLE PRECISION DEFAULT NULL, CHANGE total_vat_inc total_vat_inc DOUBLE PRECISION DEFAULT NULL, CHANGE note note VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE command_detail CHANGE price_vat_exc price_vat_exc DOUBLE PRECISION DEFAULT NULL, CHANGE price_vat_inc price_vat_inc DOUBLE PRECISION DEFAULT NULL, CHANGE vat_percent vat_percent DOUBLE PRECISION DEFAULT NULL, CHANGE amount_vat_exc amount_vat_exc DOUBLE PRECISION DEFAULT NULL, CHANGE amount_vat_inc amount_vat_inc DOUBLE PRECISION DEFAULT NULL, CHANGE quantity quantity SMALLINT UNSIGNED DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE command_status CHANGE text_color text_color VARCHAR(30) DEFAULT NULL, CHANGE bg_color bg_color VARCHAR(30) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE comment CHANGE rating rating SMALLINT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE configuration CHANGE language_id language_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE currency_id currency_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE site_name site_name VARCHAR(255) DEFAULT NULL, CHANGE description description VARCHAR(512) DEFAULT NULL, CHANGE admin_email admin_email VARCHAR(255) DEFAULT NULL, CHANGE format_facture format_facture VARCHAR(50) DEFAULT NULL, CHANGE reference_facture reference_facture VARCHAR(50) DEFAULT NULL, CHANGE format_livraison format_livraison VARCHAR(50) DEFAULT NULL, CHANGE reference_livraison reference_livraison VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE country CHANGE language_id language_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE currency_id currency_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE email CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE email_history CHANGE subject subject VARCHAR(255) DEFAULT NULL, CHANGE sender sender VARCHAR(255) DEFAULT NULL, CHANGE receiver receiver VARCHAR(255) DEFAULT NULL, CHANGE bill bill VARCHAR(255) DEFAULT NULL, CHANGE ship ship VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE email_lang CHANGE subject subject VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE language CHANGE date_format date_format VARCHAR(50) DEFAULT NULL, CHANGE price_format price_format VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE notification CHANGE has_bill has_bill TINYINT(1) DEFAULT NULL, CHANGE has_ship has_ship TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE post CHANGE parent_id parent_id BIGINT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE post_lang CHANGE author_id author_id INT UNSIGNED DEFAULT NULL, CHANGE title title VARCHAR(255) DEFAULT NULL, CHANGE description description VARCHAR(512) DEFAULT NULL, CHANGE keywords keywords VARCHAR(255) DEFAULT NULL, CHANGE status status VARCHAR(100) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE product ADD image_id BIGINT UNSIGNED DEFAULT NULL, ADD is_active TINYINT(1) NOT NULL, CHANGE brand_id brand_id BIGINT UNSIGNED DEFAULT NULL, CHANGE aen13 aen13 VARCHAR(13) DEFAULT NULL, CHANGE width width SMALLINT DEFAULT NULL, CHANGE height height SMALLINT DEFAULT NULL, CHANGE length length SMALLINT DEFAULT NULL, CHANGE weight weight SMALLINT DEFAULT NULL, CHANGE volume volume SMALLINT DEFAULT NULL, CHANGE quantity_min quantity_min SMALLINT DEFAULT NULL, CHANGE quantity_max quantity_max SMALLINT DEFAULT NULL, CHANGE is_new is_new TINYINT(1) DEFAULT NULL, CHANGE is_featured is_featured TINYINT(1) DEFAULT NULL, CHANGE is_promotion is_promotion TINYINT(1) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD3DA5256D FOREIGN KEY (image_id) REFERENCES post (id)');
        $this->addSql('CREATE INDEX IDX_D34A04AD3DA5256D ON product (image_id)');
        $this->addSql('ALTER TABLE product_price CHANGE price_vat_exc price_vat_exc DOUBLE PRECISION DEFAULT NULL, CHANGE price_vat_inc price_vat_inc DOUBLE PRECISION DEFAULT NULL, CHANGE status status VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE product_promotion CHANGE price_vat_exc price_vat_exc DOUBLE PRECISION DEFAULT NULL, CHANGE price_vat_inc price_vat_inc DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE product_shipping CHANGE currency_id currency_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE country_id country_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE price price DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE promotion CHANGE offered_id offered_id INT UNSIGNED DEFAULT NULL, CHANGE percent percent DOUBLE PRECISION DEFAULT NULL, CHANGE count count SMALLINT UNSIGNED DEFAULT NULL, CHANGE amount_vat_exc amount_vat_exc DOUBLE PRECISION DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE shipping CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL, CHANGE price price DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE user CHANGE language_id language_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE avatar_id avatar_id BIGINT UNSIGNED DEFAULT NULL, CHANGE first_name first_name VARCHAR(150) DEFAULT NULL, CHANGE last_name last_name VARCHAR(150) DEFAULT NULL, CHANGE roles roles VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE user_address CHANGE type_id type_id SMALLINT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE vat CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE vat_lang CHANGE language_id language_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE label label VARCHAR(150) DEFAULT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE address CHANGE city_id city_id INT UNSIGNED DEFAULT NULL, CHANGE country_id country_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE line2 line2 VARCHAR(150) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE zip_code zip_code VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE longitude longitude DOUBLE PRECISION DEFAULT \'NULL\', CHANGE latitude latitude DOUBLE PRECISION DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE city CHANGE country_id country_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE command CHANGE user_id user_id INT UNSIGNED DEFAULT NULL, CHANGE shipping_id shipping_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE status_id status_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE billing_address_id billing_address_id INT UNSIGNED DEFAULT NULL, CHANGE shipping_address_id shipping_address_id INT UNSIGNED DEFAULT NULL, CHANGE session_id session_id VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE reference reference VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE sub_total_vat_exc sub_total_vat_exc DOUBLE PRECISION DEFAULT \'NULL\', CHANGE sub_total_vat_inc sub_total_vat_inc DOUBLE PRECISION DEFAULT \'NULL\', CHANGE total_vat total_vat DOUBLE PRECISION DEFAULT \'NULL\', CHANGE reduction_label reduction_label VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE reduction reduction DOUBLE PRECISION DEFAULT \'NULL\', CHANGE shipping_label shipping_label VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE shipping_value shipping_value DOUBLE PRECISION DEFAULT \'NULL\', CHANGE total_vat_inc total_vat_inc DOUBLE PRECISION DEFAULT \'NULL\', CHANGE note note VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE command_detail CHANGE price_vat_exc price_vat_exc DOUBLE PRECISION DEFAULT \'NULL\', CHANGE price_vat_inc price_vat_inc DOUBLE PRECISION DEFAULT \'NULL\', CHANGE vat_percent vat_percent DOUBLE PRECISION DEFAULT \'NULL\', CHANGE amount_vat_exc amount_vat_exc DOUBLE PRECISION DEFAULT \'NULL\', CHANGE amount_vat_inc amount_vat_inc DOUBLE PRECISION DEFAULT \'NULL\', CHANGE quantity quantity SMALLINT UNSIGNED DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE command_status CHANGE text_color text_color VARCHAR(30) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE bg_color bg_color VARCHAR(30) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE comment CHANGE rating rating SMALLINT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE configuration CHANGE language_id language_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE currency_id currency_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE site_name site_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE description description VARCHAR(512) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE admin_email admin_email VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE format_facture format_facture VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE reference_facture reference_facture VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE format_livraison format_livraison VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE reference_livraison reference_livraison VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE country CHANGE language_id language_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE currency_id currency_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE email CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE email_history CHANGE subject subject VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE sender sender VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE receiver receiver VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE bill bill VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ship ship VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE email_lang CHANGE subject subject VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE language CHANGE date_format date_format VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE price_format price_format VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE notification CHANGE has_bill has_bill TINYINT(1) DEFAULT \'NULL\', CHANGE has_ship has_ship TINYINT(1) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE post CHANGE parent_id parent_id BIGINT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE post_lang CHANGE author_id author_id INT UNSIGNED DEFAULT NULL, CHANGE title title VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE description description VARCHAR(512) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE keywords keywords VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE status status VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD3DA5256D');
        $this->addSql('DROP INDEX IDX_D34A04AD3DA5256D ON product');
        $this->addSql('ALTER TABLE product DROP image_id, DROP is_active, CHANGE brand_id brand_id BIGINT UNSIGNED DEFAULT NULL, CHANGE aen13 aen13 VARCHAR(13) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE width width SMALLINT DEFAULT NULL, CHANGE height height SMALLINT DEFAULT NULL, CHANGE length length SMALLINT DEFAULT NULL, CHANGE weight weight SMALLINT DEFAULT NULL, CHANGE volume volume SMALLINT DEFAULT NULL, CHANGE quantity_min quantity_min SMALLINT DEFAULT NULL, CHANGE quantity_max quantity_max SMALLINT DEFAULT NULL, CHANGE is_new is_new TINYINT(1) DEFAULT \'NULL\', CHANGE is_featured is_featured TINYINT(1) DEFAULT \'NULL\', CHANGE is_promotion is_promotion TINYINT(1) DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE product_price CHANGE price_vat_exc price_vat_exc DOUBLE PRECISION DEFAULT \'NULL\', CHANGE price_vat_inc price_vat_inc DOUBLE PRECISION DEFAULT \'NULL\', CHANGE status status VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE product_promotion CHANGE price_vat_exc price_vat_exc DOUBLE PRECISION DEFAULT \'NULL\', CHANGE price_vat_inc price_vat_inc DOUBLE PRECISION DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE product_shipping CHANGE currency_id currency_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE country_id country_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE price price DOUBLE PRECISION DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE promotion CHANGE offered_id offered_id INT UNSIGNED DEFAULT NULL, CHANGE percent percent DOUBLE PRECISION DEFAULT \'NULL\', CHANGE count count SMALLINT UNSIGNED DEFAULT NULL, CHANGE amount_vat_exc amount_vat_exc DOUBLE PRECISION DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE shipping CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\', CHANGE price price DOUBLE PRECISION DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE user CHANGE language_id language_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE avatar_id avatar_id BIGINT UNSIGNED DEFAULT NULL, CHANGE first_name first_name VARCHAR(150) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE last_name last_name VARCHAR(150) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE roles roles VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE user_address CHANGE type_id type_id SMALLINT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE vat CHANGE description description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE deleted_at deleted_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE vat_lang CHANGE language_id language_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE label label VARCHAR(150) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
    }
}
